
spring.application.name=bookverse-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/bookverse
spring.datasource.username=postgres
spring.datasource.password=Adithyan@2025

spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8080